use serde::{Deserialize, Serialize};

#[derive(Deserialize, PartialEq, Eq, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum WaypointTrait {
    Uncharted,
    Marketplace,
    Shipyard,
    Outpost,
    Scatteredsettlements,
    Sprawlingcities,
    Megastructures,
    Overcrowded,
    Hightech,
    Corrupt,
    Bureaucratic,
    Tradinghub,
    Industrial,
    Blackmarket,
    Researchfacility,
    Militarybase,
    Surveillanceoutpost,
    Explorationoutpost,
    Mineraldeposits,
    Commonmetaldeposits,
    Preciousmetaldeposits,
    Raremetaldeposits,
    Methanepools,
    Icecrystals,
    Explosivegases,
    Strongmagnetosphere,
    Vibrantauroras,
    Saltflats,
    Canyons,
    Perpetualdaylight,
    Perpetualovercast,
    Dryseabeds,
    Magmaseas,
    Supervolcanoes,
    Ashclouds,
    Vastruins,
    Mutatedflora,
    Terraformed,
    Extremetemperatures,
    Extremepressure,
    Diverselife,
    Scarcelife,
    Fossils,
    Weakgravity,
    Stronggravity,
    Crushinggravity,
    Toxicatmosphere,
    Corrosiveatmosphere,
    Breathableatmosphere,
    Jovian,
    Rocky,
    Volcanic,
    Frozen,
    Swamp,
    Barren,
    Temperate,
    Jungle,
    Ocean,
    Stripped,
}

#[derive(Deserialize, PartialEq, Eq, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum WaypointType {
    Planet,
    Gasgiant,
    Moon,
    Orbitalstation,
    Jumpgate,
    Asteroidfield,
    Nebula,
    Debrisfield,
    Gravitywell,
}

#[derive(Deserialize, PartialEq, Eq, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SystemType {
    Neutronstar,
    Redstar,
    Orangestar,
    Bluestar,
    Youngstar,
    Whitedwarf,
    Blackhole,
    Hypergiant,
    Nebula,
    Unstable,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ShipType {
    Shipprobe,
    Shipminingdrone,
    Shipinterceptor,
    Shiplighthauler,
    Shipcommandfrigate,
    Shipexplorer,
    Shipheavyfreighter,
    Shiplightshuttle,
    Shiporehound,
    Shiprefiningfreighter,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ShipRole {
    Fabricator,
    Harvester,
    Hauler,
    Interceptor,
    Excavator,
    Transport,
    Repair,
    Surveyor,
    Command,
    Carrier,
    Patrol,
    Satellite,
    Explorer,
    Refinery,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ShipReactorType {
    Reactorsolari,
    Reactorfusioni,
    Reactorfissioni,
    Reactorchemicali,
    Reactorantimatteri,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ShipNavStatus {
    Intransit,
    Inorbit,
    Docked,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ShipMount {
    Mountgassiphoni,
    Mountgassiphonii,
    Mountgassiphoniii,
    Mountsurveyori,
    Mountsurveyorii,
    Mountsurveyoriii,
    Mountsensorarrayi,
    Mountsensorarrayii,
    Mountsensorarrayiii,
    Mountmininglaseri,
    Mountmininglaserii,
    Mountmininglaseriii,
    Mountlasercannoni,
    Mountmissilelauncheri,
    Mountturreti,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TradeSymbol {
    Preciousstones,
    Quartzsand,
    Siliconcrystals,
    Ammoniaice,
    Liquidhydrogen,
    Liquidnitrogen,
    Icewater,
    Exoticmatter,
    Advancedcircuitry,
    Gravitonemitters,
    Iron,
    Ironore,
    Copper,
    Copperore,
    Aluminum,
    Aluminumore,
    Silver,
    Silverore,
    Gold,
    Goldore,
    Platinum,
    Platinumore,
    Diamonds,
    Uranite,
    Uraniteore,
    Meritium,
    Meritiumore,
    Hydrocarbon,
    Antimatter,
    Fertilizers,
    Fabrics,
    Food,
    Jewelry,
    Machinery,
    Firearms,
    Assaultrifles,
    Militaryequipment,
    Explosives,
    Labinstruments,
    Ammunition,
    Electronics,
    Shipplating,
    Equipment,
    Fuel,
    Medicine,
    Drugs,
    Clothing,
    Microprocessors,
    Plastics,
    Polynucleotides,
    Biocomposites,
    Nanobots,
    Aimainframes,
    Quantumdrives,
    Roboticdrones,
    Cyberimplants,
    Genetherapeutics,
    Neuralchips,
    Moodregulators,
    Viralagents,
    Microfusiongenerators,
    Supergrains,
    Laserrifles,
    Holographics,
    Shipsalvage,
    Relictech,
    Novellifeforms,
    Botanicalspecimens,
    Culturalartifacts,
    Reactorsolari,
    Reactorfusioni,
    Reactorfissioni,
    Reactorchemicali,
    Reactorantimatteri,
    Engineimpulsedrivei,
    Engineiondrivei,
    Engineiondriveii,
    Enginehyperdrivei,
    Modulemineralprocessori,
    Modulecargoholdi,
    Modulecrewquartersi,
    Moduleenvoyquartersi,
    Modulepassengercabini,
    Modulemicrorefineryi,
    Moduleorerefineryi,
    Modulefuelrefineryi,
    Modulesciencelabi,
    Modulejumpdrivei,
    Modulejumpdriveii,
    Modulejumpdriveiii,
    Modulewarpdrivei,
    Modulewarpdriveii,
    Modulewarpdriveiii,
    Moduleshieldgeneratori,
    Moduleshieldgeneratorii,
    Mountgassiphoni,
    Mountgassiphonii,
    Mountgassiphoniii,
    Mountsurveyori,
    Mountsurveyorii,
    Mountsurveyoriii,
    Mountsensorarrayi,
    Mountsensorarrayii,
    Mountsensorarrayiii,
    Mountmininglaseri,
    Mountmininglaserii,
    Mountmininglaseriii,
    Mountlasercannoni,
    Mountmissilelauncheri,
    Mountturreti,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ShipModule {
    Modulemineralprocessori,
    Modulecargoholdi,
    Modulecrewquartersi,
    Moduleenvoyquartersi,
    Modulepassengercabini,
    Modulemicrorefineryi,
    Moduleorerefineryi,
    Modulefuelrefineryi,
    Modulesciencelabi,
    Modulejumpdrivei,
    Modulejumpdriveii,
    Modulejumpdriveiii,
    Modulewarpdrivei,
    Modulewarpdriveii,
    Modulewarpdriveiii,
    Moduleshieldgeneratori,
    Moduleshieldgeneratorii,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ShipFram {
    Frameprobe,
    Framedrone,
    Frameinterceptor,
    Frameracer,
    Framefighter,
    Framefrigate,
    Frameshuttle,
    Frameexplorer,
    Frameminer,
    Framelightfreighter,
    Frameheavyfreighter,
    Frametransport,
    Framedestroyer,
    Framecruiser,
    Framecarrier,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ShipEngine {
    Engineimpulsedrivei,
    Engineiondrivei,
    Engineiondriveii,
    Enginehyperdrivei,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TradeGood {
    Preciousstones,
    Quartzsand,
    Siliconcrystals,
    Ammoniaice,
    Liquidhydrogen,
    Liquidnitrogen,
    Icewater,
    Exoticmatter,
    Advancedcircuitry,
    Gravitonemitters,
    Iron,
    Ironore,
    Copper,
    Copperore,
    Aluminum,
    Aluminumore,
    Silver,
    Silverore,
    Gold,
    Goldore,
    Platinum,
    Platinumore,
    Diamonds,
    Uranite,
    Uraniteore,
    Meritium,
    Meritiumore,
    Hydrocarbon,
    Antimatter,
    Fertilizers,
    Fabrics,
    Food,
    Jewelry,
    Machinery,
    Firearms,
    Assaultrifles,
    Militaryequipment,
    Explosives,
    Labinstruments,
    Ammunition,
    Electronics,
    Shipplating,
    Equipment,
    Fuel,
    Medicine,
    Drugs,
    Clothing,
    Microprocessors,
    Plastics,
    Polynucleotides,
    Biocomposites,
    Nanobots,
    Aimainframes,
    Quantumdrives,
    Roboticdrones,
    Cyberimplants,
    Genetherapeutics,
    Neuralchips,
    Moodregulators,
    Viralagents,
    Microfusiongenerators,
    Supergrains,
    Laserrifles,
    Holographics,
    Shipsalvage,
    Relictech,
    Novellifeforms,
    Botanicalspecimens,
    Culturalartifacts,
    Reactorsolari,
    Reactorfusioni,
    Reactorfissioni,
    Reactorchemicali,
    Reactorantimatteri,
    Engineimpulsedrivei,
    Engineiondrivei,
    Engineiondriveii,
    Enginehyperdrivei,
    Modulemineralprocessori,
    Modulecargoholdi,
    Modulecrewquartersi,
    Moduleenvoyquartersi,
    Modulepassengercabini,
    Modulemicrorefineryi,
    Moduleorerefineryi,
    Modulefuelrefineryi,
    Modulesciencelabi,
    Modulejumpdrivei,
    Modulejumpdriveii,
    Modulejumpdriveiii,
    Modulewarpdrivei,
    Modulewarpdriveii,
    Modulewarpdriveiii,
    Moduleshieldgeneratori,
    Moduleshieldgeneratorii,
    Mountgassiphoni,
    Mountgassiphonii,
    Mountgassiphoniii,
    Mountsurveyori,
    Mountsurveyorii,
    Mountsurveyoriii,
    Mountsensorarrayi,
    Mountsensorarrayii,
    Mountsensorarrayiii,
    Mountmininglaseri,
    Mountmininglaserii,
    Mountmininglaseriii,
    Mountlasercannoni,
    Mountmissilelauncheri,
    Mountturreti,
}

#[derive(Serialize, Deserialize, Debug)]
pub enum FlightMode {
    #[serde(alias = "CRUISE")]
    Cruise,
    #[serde(alias = "BURN")]
    Burn,
    #[serde(alias = "DRIFT")]
    Drift,
    #[serde(alias = "STEALTH")]
    Stealth,
}
