name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: deps
        run: sudo apt-get update && apt-get install -y build-essential pkg-config libssl-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - uses: actions-rs/cargo@v1
        with:
          command: test
          
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
        
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: my-spacetraders.bin
          path: target/release/interface

  docker-build:
    name: Docker Build
    needs: build-and-test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Bin
        uses: actions/download-artifact@v3

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@main
        with:
          registry: registry.sawyer.services
          platforms: linux/amd64,linux/arm64

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}
