name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: deps
        run: sudo apt-get update && apt-get install -y build-essential pkg-config libssl-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - uses: actions-rs/cargo@v1
        with:
          command: test
          
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: my-spacetraders
          path: target/release/my-spacetraders.bin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: registry.sawyer.services/my-spacetraders:latest
